namespace MyUserApp.Models
{
    /// <summary>
    /// Defines the distinct types of authors that can create an annotation.
    /// Using an enumeration provides type safety and improves code clarity.
    /// </summary>
    public enum AuthorType
    {
        /// <summary>
        /// An annotation created by an Inspector.
        /// </summary>
        Inspector,

        /// <summary>
        /// An annotation created by a Verifier.
        /// </summary>
        Verifier,

        /// <summary>
        /// An annotation generated by the AI analysis tool.
        /// </summary>
        AI
    }
}